spring:
  application:
    name: auth-app
  datasource:
    url: jdbc:postgresql://localhost:5432/yinnohs-auth
    username: yinnohs
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 5052

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


argon2:
  memory: 7168
  iterations: 5
  parallelism: 1
  saltLength: 2
